"""Add score_id to NoteData

Revision ID: 77898099f6ca
Revises: 
Create Date: 2024-10-27 12:45:40.498741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77898099f6ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('note_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measure', sa.Integer(), nullable=False),
    sa.Column('note_name', sa.String(length=10), nullable=False),
    sa.Column('duration', sa.String(length=10), nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['score_id'], ['score.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['note_data.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_analysis')
    op.drop_table('note_data')
    op.drop_table('user')
    op.drop_table('score')
    # ### end Alembic commands ###
